-- ---------- CORE USERS & ROLES ----------
CREATE TABLE users (
	user_id 			BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	username 			VARCHAR(30) UNIQUE NOT NULL,
	first_name 			VARCHAR(50) NOT NULL,
	last_name 			VARCHAR(50) NOT NULL,
	email 				VARCHAR(255) UNIQUE NOT NULL,
	password 			VARCHAR(255) NOT NULL,
	dob 				DATE NOT NULL,
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
	role_id 			BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	role_name 			VARCHAR(20) UNIQUE NOT NULL,
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_roles (
	user_id 			BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
	role_id 			BIGINT REFERENCES roles(role_id) ON DELETE CASCADE,
	PRIMARY KEY (user_id, role_id),
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ---------- ROLE PROFILES ----------
CREATE TABLE admins (
	user_id 			BIGINT PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE vendors (
	user_id 			BIGINT PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
	store_name 			VARCHAR(100) NOT NULL,
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customers (
	user_id 			BIGINT PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ---------- CONTACT INFO ----------
CREATE TABLE phone_numbers (
	phone_id 			BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	phone_number 		VARCHAR(20) UNIQUE NOT NULL,
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_phone_numbers (
	user_id 			BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
	phone_id 			BIGINT REFERENCES phone_numbers(phone_id) ON DELETE CASCADE,
	PRIMARY KEY (user_id, phone_id),
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE addresses (
	address_id 			BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id 			BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
	address1 			VARCHAR(100) NOT NULL,
	address2 			VARCHAR(100),
	city 				VARCHAR(50) NOT NULL,
	state 				VARCHAR(50) NOT NULL,
	country 			VARCHAR(50) NOT NULL,
	postalCode 			VARCHAR(20) NOT NULL,
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ---------- PRODUCTS ----------
CREATE TABLE products (
	product_id 			BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	vendor_id 			BIGINT REFERENCES vendors(user_id) ON DELETE CASCADE,
	name 				VARCHAR(100) NOT NULL,
	description 		TEXT,
	price 				NUMERIC(12,2) NOT NULL,
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE product_specs (
	spec_id 			BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	product_id 			BIGINT REFERENCES products(product_id) ON DELETE CASCADE,
	specification 		VARCHAR(255) NOT NULL,
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE product_colors (
	color_id 			BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	color_name 			VARCHAR(50) NOT NULL,
	hex_code 			VARCHAR(7) NOT NULL,
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE product_categories (
	category_id 		BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	category_name 		VARCHAR(50) UNIQUE NOT NULL,
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE product_images (
	image_id 			BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	product_id 			BIGINT REFERENCES products(product_id) ON DELETE CASCADE,
	image_url 			TEXT NOT NULL,
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ---------- CARTS & WISHLISTS ----------
CREATE TABLE carts (
	cart_id 			BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	customer_id 		BIGINT REFERENCES customers(user_id) ON DELETE CASCADE,
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cart_items (
	cart_item_id 		BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	cart_id 			BIGINT REFERENCES carts(cart_id) ON DELETE CASCADE,
	product_id 			BIGINT REFERENCES products(product_id) ON DELETE CASCADE,
	quantity 			INT NOT NULL CHECK (quantity > 0),
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE wishlists (
	wishlist_id 		BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	customer_id 		BIGINT REFERENCES customers(user_id) ON DELETE CASCADE,
	title 				VARCHAR(100) NOT NULL,
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE wishlist_items (
	wishlist_item_id 	BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	wishlist_id 		BIGINT REFERENCES wishlists(wishlist_id) ON DELETE CASCADE,
	product_id 			BIGINT REFERENCES products(product_id) ON DELETE CASCADE,
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ---------- ORDERS ----------
CREATE TABLE orders (
	order_id 			BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	customer_id 		BIGINT REFERENCES customers(user_id),
	order_status 		VARCHAR(20) NOT NULL,
	amount 				NUMERIC(12,2) NOT NULL,
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_items (
	order_item_id 		BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	order_id 			BIGINT REFERENCES orders(order_id) ON DELETE CASCADE,
	product_id 			BIGINT REFERENCES products(product_id),
	quantity 			INT NOT NULL,
	price_at_purchase 	NUMERIC(12,2) NOT NULL,
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_addresses (
	order_id 			BIGINT REFERENCES orders(order_id) ON DELETE CASCADE,
	address_id 			BIGINT REFERENCES addresses(address_id),
	address_type 		VARCHAR(20) CHECK (address_type IN ('shipping', 'billing')),
	PRIMARY KEY (order_id, address_type),
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ---------- PAYMENTS ----------
CREATE TABLE payments (
	payment_id 			BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	order_id 			BIGINT REFERENCES orders(order_id) ON DELETE CASCADE,
	amount 				NUMERIC(12,2) NOT NULL,
	payment_method 		VARCHAR(30) NOT NULL,
	paid_at 				TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ---------- REVIEWS ----------
CREATE TABLE reviews (
	review_id 			BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	rating 				INT CHECK (rating BETWEEN 1 AND 5),
	title 				VARCHAR(100) NOT NULL,
	description 		TEXT,
	created_at 			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at			TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	customer_id 		BIGINT REFERENCES customers(user_id) ON DELETE CASCADE,
	product_id 			BIGINT REFERENCES products(product_id) ON DELETE CASCADE,
	UNIQUE (customer_id, product_id)
);


CREATE OR REPLACE FUNCTION setUpdatedAt()
RETURNS TRIGGER AS $$
BEGIN
	NEW.updated_at = CURRENT_TIMESTAMP;
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER usersUpdatedAt
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER paymentsUpdatedAt 
BEFORE UPDATE ON payments
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER orderItemsUpdatedAt 
BEFORE UPDATE ON order_items
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER orderAddressesUpdatedAt 
BEFORE UPDATE ON order_addresses 
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER ordersUpdatedAt 
BEFORE UPDATE ON orders
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER productImagesUpdatedAt 
BEFORE UPDATE ON product_images
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER productCategoriesUpdatedAt 
BEFORE UPDATE ON product_categories
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER productColorsUpdatedAt 
BEFORE UPDATE ON product_colors
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER productSpecsUpdatedAt
BEFORE UPDATE ON product_specs
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER productsUpdatedAt 
BEFORE UPDATE ON products
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER reviewsUpdatedAt 
BEFORE UPDATE ON reviews
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER wishlistItemsUpdatedAt 
BEFORE UPDATE ON wishlist_items
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER wishlistsUpdatedAt 
BEFORE UPDATE ON wishlists
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER cartItemsUpdatedAt 
BEFORE UPDATE ON cart_items
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER cartsUpdatedAt 
BEFORE UPDATE ON carts
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER userPhoneNumbersUpdatedAt 
BEFORE UPDATE ON user_phone_numbers
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER phoneNumbersUpdatedAt 
BEFORE UPDATE ON phone_numbers
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER addressesUpdatedAt 
BEFORE UPDATE ON addresses
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER vendorsUpdatedAt 
BEFORE UPDATE ON vendors
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER customersUpdatedAt 
BEFORE UPDATE ON customers
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER adminsUpdatedAt 
BEFORE UPDATE ON admins
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER userRolesUpdatedAt 
BEFORE UPDATE ON user_roles
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER rolesUpdatedAt 
BEFORE UPDATE ON roles
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE OR REPLACE TRIGGER usersUpdatedAt 
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();